App.Variant = DS.Model.extend
  name: DS.attr 'string'
  sku: DS.attr 'string'
  price: DS.attr 'string'
  weight: DS.attr 'string'
  height: DS.attr 'string'
  width: DS.attr 'string'
  depth: DS.attr 'string'
  is_master: DS.attr 'boolean'
  slug: DS.attr 'string'
  description: DS.attr 'string'
  track_inventory: DS.attr 'boolean'
  instock_description: DS.attr 'string'
  display_price: DS.attr 'string'
  total_on_hand: DS.attr 'number'
  options_text: DS.attr 'string'

  images: DS.hasMany 'image'
  option_values: DS.hasMany 'option_value'
  product: DS.belongsTo 'product'
  variant_colors: DS.attr 'object'


  catalogue_image: Em.computed.alias 'product.catalogue_image'
  type: Em.computed.alias 'product.product_type'
  category: Em.computed.alias 'product.product_category'
